Release v0.0.2

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -3,53 +3,77 @@ image: ubuntu:18.04
 stages:
   - build
   - deploy
-  - clean-up
 
 variables:
-  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$DEPLOY_TAG
-  TAG_LATEST: $CI_REGISTRY_IMAGE/rockship/$CI_COMMIT_REF_NAME:$DEPLOY_TAG
+  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME
+  TAG_LATEST: $CI_REGISTRY_IMAGE/rockship/$CI_COMMIT_REF_NAME
+
 
 before_script:
-  - test -n "$SSH_PRIVATE_KEY" || ( echo "missing variable SSH_PRIVATE_KEY" && exit 1)
-  - test -n "$SSH_HOST" || ( echo "missing variable SSH_HOST" && exit 1)
-  - test -n "$PROJECT_DIR" || ( echo "missing variable PROJECT_DIR" && exit 1)
-  - test -n "$ROCKSHIP_REGISTRY_USERNAE" || ( echo "missing variable ROCKSHIP_REGISTRY_USERNAE" && exit 1)
-  - test -n "$ROCKSHIP_REGISTRY_PASSWORD" || ( echo "missing variable ROCKSHIP_REGISTRY_PASSWORD" && exit 1)
-  - test -n "$CI_REGISTRY_IMAGE" || ( echo "missing variable CI_REGISTRY" && exit 1)
-  - apt-get update -qq && apt-get install -qq curl
-  - which ssh-agent || apt-get install -qq openssh-client
-  - eval $(ssh-agent -s)
-  - ssh-add <(echo "$SSH_PRIVATE_KEY")
-  - mkdir -p ~/.ssh
-  - chmod 700 ~/.ssh
-  - touch ~/.ssh/known_hosts
-  - chmod 644 ~/.ssh/known_hosts
-  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
+  - >
+    if ["$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH"]; then
+      DEPLOY_TAG="prod"
+    else
+      DEPLOY_TAG="stg"
+    fi
+
+.install_ssh:
+  before_script:
+    - test -n "$SSH_PRIVATE_KEY" || ( echo "missing variable SSH_PRIVATE_KEY" && exit 1)
+    - test -n "$SSH_HOST" || ( echo "missing variable SSH_HOST" && exit 1)
+    - test -n "$PROJECT_DIR" || ( echo "missing variable PROJECT_DIR" && exit 1)
+    - test -n "$ROCKSHIP_REGISTRY_USERNAE" || ( echo "missing variable ROCKSHIP_REGISTRY_USERNAE" && exit 1)
+    - test -n "$ROCKSHIP_REGISTRY_PASSWORD" || ( echo "missing variable ROCKSHIP_REGISTRY_PASSWORD" && exit 1)
+    - test -n "$CI_REGISTRY_IMAGE" || ( echo "missing variable CI_REGISTRY" && exit 1)
+    - apt-get update -qq && apt-get install -qq curl
+    - which ssh-agent || apt-get install -qq openssh-client
+    - eval $(ssh-agent -s)
+    - ssh-add <(echo "$SSH_PRIVATE_KEY")
+    - mkdir -p ~/.ssh
+    - chmod 700 ~/.ssh
+    - touch ~/.ssh/known_hosts
+    - chmod 644 ~/.ssh/known_hosts
+    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
+    - >
+      if ["$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH"]; then
+        DEPLOY_TAG="prod"
+      else
+        DEPLOY_TAG="stg"
+      fi
 
 build:
-  stage: build
+  stage: build 
+  image:
+    name: gcr.io/kaniko-project/executor:v1.10.0-debug
+    entrypoint: [""]
+  script:
+    - echo "{\"auths\":{\"${CI_REGISTRY_IMAGE}\":{\"auth\":\"$(printf "%s:%s" "${ROCKSHIP_REGISTRY_USERNAE}" "${ROCKSHIP_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
+    - /kaniko/executor
+      --context "${CI_PROJECT_DIR}"
+      --build-arg BOT_PRIVATE_TOKEN=$BOT_PRIVATE_TOKEN
+      --image-name-tag-with-digest-file "$TAG_LATEST:$DEPLOY_TAG"
+      --dockerfile "${CI_PROJECT_DIR}/builder/Dockerfile"
+      --destination "$TAG_LATEST:$DEPLOY_TAG"
   tags:
     - self-host
-  script:
-    - ssh $SSH_BUILD_HOST "cd src/$PROJECT_DIR && git checkout $CI_COMMIT_BRANCH && git pull && docker login -u $ROCKSHIP_REGISTRY_USERNAE -p $ROCKSHIP_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE && make build-image-local commit=$TAG_COMMIT latest=$TAG_LATEST"
   only:
     - devops/test
     - master
     - dev
 
 deploy:
+  extends: .install_ssh
   stage: deploy
   tags:
     - self-host
   script:
-    - echo $CI_COMMIT_REF_NAME
-    - echo $DEPLOY_TAG
-    - ssh $SSH_HOST "cd monorepo/aegon && docker login -u $ROCKSHIP_REGISTRY_USERNAE -p $ROCKSHIP_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE && docker pull $TAG_LATEST && make blueprint-construct service=$CI_COMMIT_REF_NAME tag=$DEPLOY_TAG"
+    - ssh $SSH_HOST "cd monorepo/aegon && docker login -u $ROCKSHIP_REGISTRY_USERNAE -p $ROCKSHIP_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE && docker pull $TAG_LATEST:$DEPLOY_TAG && make blueprint-construct service=$CI_COMMIT_REF_NAME tag=$DEPLOY_TAG"
   only:
     - devops/test
     - dev
 
 deploy-production:
+  extends: .install_ssh
   stage: deploy
   tags:
     - self-host
@@ -57,18 +81,9 @@ deploy-production:
     name: production
     url: https://rockship.co
   script:
-    - ssh $SSH_HOST "cd monorepo/aegon && docker login -u $ROCKSHIP_REGISTRY_USERNAE -p $ROCKSHIP_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE && docker pull $TAG_LATEST && make blueprint-construct service=$CI_COMMIT_REF_NAME tag=$DEPLOY_TAG"
+    - echo $DEPLOY_TAG
+    - echo $TAG_LATEST:$DEPLOY_TAG
+    - ssh $SSH_HOST "cd monorepo/aegon && docker login -u $ROCKSHIP_REGISTRY_USERNAE -p $ROCKSHIP_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE && docker pull $TAG_LATEST:$DEPLOY_TAG && make blueprint-construct service=$CI_COMMIT_REF_NAME tag=$DEPLOY_TAG"
   rules:
     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
       when: manual
-
-clean-up:
-  stage: clean-up
-  tags:
-    - self-host
-  script:
-    - ssh $SSH_BUILD_HOST "docker rmi $TAG_COMMIT && docker rmi $TAG_LATEST"
-  only:
-    - devops/test
-    - dev
-    - master
